language: java
jdk:
  - oraclejdk8
  - junit

jobs:
  include:
    - stage: "Getting maven wrapper"
      install:
        - mvn -N io.takari:maven:wrapper
        - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
    - stage: unit tests
      script: "Running unit tests (1)"
    - stage: unit tests
      script: "Running unit tests (2)"
    - stage: deploy to production
      script: skip
      deploy:
        provider: heroku
        app: chrono-omega
        api_key: $HEROKU_AUTH_TOKEN
    - stage: test production
      script: 'curl https://chrono-omega.herokuapp.com/'